database:
  address: ""
  port: 3306
  username: ""
  password: ""
  database: ""
twitch:
  broadcaster: 0
http:
  port: 8000

JDBC_URL: "jdbc:mysql://localhost:3306/test"
DB_USERNAME: "admin"
DB_PASSWORD: "password"
PORT: 8000
BROADCASTER_ID: