name: TwitchIntegration
main: tk.camikase.TwitchIntegration.TwitchIntegrationPlugin
version: 1.0.1
author: CamiKase
api-version: 1.13
depend: [PlayerKits, LuckPerms]

commands:
  claimsub:
    description: Reclamar el rol de sub
    usage: /<command>
